### ISSUE TITLE
How do I use an alias?

### ISSUE THREAD

**Issue by gailmiller** [aws-samples/aws-lex-web-ui#123]
I would like to use a Lex version alias in here, but I cant seem to find all the places to set it.  Where should I be looking apart from a global search and replace for $Latest (which doesnt really help me understand anything)

Cheers,
Gail

**Comment by bobpskier** [comment]
As you indicate, the current source only points at $LATEST when making Lex requests. I think the best approach would be to add a configuration parameter to the lex-web-ui-loader-config.json file. Just like there is a 'botName' property, a 'botAlias' property could be introduced. Then the lex-web-ui could target the bot's alias or adjusted to use a new alias using this configuration parameter. Ultimately the file lex-web-ui/src/lib/lex/client.js will be modified to utilize this parameter instead of the default '$LATEST' which is assigned to botAlias in the constructor defined in client.js. I do think this enhancement needs to be made. I'll see if I can push this along over the next week or so.

**Comment by gailmiller** [comment]
That would be wonderful.  I am obviously having dev vs prod issues.  At the moment I have created 2 bots to get around it, but that isnt utilising the versioning system properly.  Especially in lambda + lex console combinations.    Thanks so much, this ui project is great!

**Comment by gailmiller** [comment]
I've just figured out how to get all this updated and working in codedeploy so Im going to have a look at the alias now :) But its looking good on initial pokes around in my dev console in chrome....

Thanks so much for the quick turn around, this will help with our deployment a great deal.

**Comment by bobpskier** [comment]
Version 0.14.4 now contains the ability to configure BotAlias used by the lex web ui.
