### ISSUE TITLE
Not able to use this cloud formation template in Ireland

### ISSUE THREAD

**Issue by ishanmourya5** [aws-samples/aws-lex-web-ui#134]
I am able to test the bot ui in N.Virginia but not able to test it in Ireland.......Any help for using this template in other regions???

**Comment by bobpskier** [comment]
The primary method to test in Ireland would be to checkout the project from github and build the project locally. The artifacts can then be upload an S3 bucket (your own bootstrap bucket) located in Ireland (eu-west-1). The lex-web-ui template could be executed in the console using Ireland as your location. Next the CF template could be run. The bootstrap bucket parameter used in the CF template would be changed to your eu-west-1 based bucket and the artifact location would be changed to just 'artifact'. This would get you past the template execution issues. 

However, I tested this process in eu-west-1 and encountered some additional code dependencies that need to be cleaned up. I'm have them resolved in my dev environment and will commit later this week after some additional testing. 

When complete I'll put them up in an S3 bucket and let you test against in Ireland using this bucket as the bootstrap bucket. Hopefully this process will be ok with you.

**Comment by ishanmourya5** [comment]
Yeah sure, share the bucket once it done....Thanks for help

**Comment by nsamuel3** [comment]
Hello Bob, wanted to check if you were able to customize the template for Ireland. Am stuck with the same issue, and would be grateful if you could help with this.


> The primary method to test in Ireland would be to checkout the project from github and build the project locally. The artifacts can then be upload an S3 bucket (your own bootstrap bucket) located in Ireland (eu-west-1). The lex-web-ui template could be executed in the console using Ireland as your location. Next the CF template could be run. The bootstrap bucket parameter used in the CF template would be changed to your eu-west-1 based bucket and the artifact location would be changed to just 'artifact'. This would get you past the template execution issues.
> 
> However, I tested this process in eu-west-1 and encountered some additional code dependencies that need to be cleaned up. I'm have them resolved in my dev environment and will commit later this week after some additional testing.
> 
> When complete I'll put them up in an S3 bucket and let you test against in Ireland using this bucket as the bootstrap bucket. Hopefully this process will be ok with you.

**Comment by MattDN93** [comment]
Hey there @nsamuel3 , @ishanmourya5 - I know this is late but if you're still interested and for others; I found a workaround to deploy this in eu-west-1 (or any other region provided all resources - Lex, Cognito, CodeBuild - work there). 

- Follow the above steps, download the following files to your own bootstrap bucket in eu-west-1:

https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-lex-web-ui/artifacts/templates/codebuild-deploy.yaml
https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-lex-web-ui/artifacts/custom-resources.zip
https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-lex-web-ui/artifacts/src.zip
https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-lex-web-ui/artifacts/templates/cognito.yaml
https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-lex-web-ui/artifacts/templates/lexbot.yaml
https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-lex-web-ui/artifacts/templates/cognitouserpoolconfig.yaml

- Make sure to use your own bucket with the same prefixes so the CloudFormation template can run normally, you should have the following files in your bucket:
**(BootStrapBucketName)/artifacts/aws-lex-web-ui/artifacts/templates/codebuild-deploy.yaml**
**(BootStrapBucketName)/artifacts/aws-lex-web-ui/artifacts**
**(BootStrapBucketName)/artifacts/aws-lex-web-ui/artifacts**

- Importantly the main CFN template is at:

https://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-lex-web-ui/artifacts/templates/master.yaml

- You'll need to download it and make the necessary changes. 

1. In your **master.yaml** CFN template modify the S3 URLs to point to their regional variants. For example, instead of 
```
https://s3.amazonaws.com/${BootstrapBucket}/${BootstrapPrefix}/templates/lexbot.yaml
```
You would replace it with the **eu-west-1** regional URL:
```
https://s3-eu-west-1.amazonaws.com/${BootstrapBucket}/${BootstrapPrefix}/templates/lexbot.yaml
```
And do the same for all the other links.

2. Now launch the Cloudformation console, select the **master.yaml** file you've edited locally and upload it. Edit the parameters as desired:
- Note the "BootstrapBucket" parameter should be the new bucket you've created with the files above
- BotName should be an existing bot in eu-west-1 unless you want to create one 
- CognitoIdentityPoolId can be an Identity Pool in eu-west-1 provided you make the changes below. If you let CloudFormation create it, make sure the bot name matches

3. Once it's all deployed, open S3 and search for the hosting bucket, should be something like **(bot-name)-codebuilddeploy-XXXXXX-webappbucket-XXXXXX**

4. Find and download the following files:
```
lex-web-ui-loader.js
lex-web-ui-loader-config.json
lex-web-ui.js
aws-config.json
```

5. Do a search-and-replace in all of these files - **replace all instances of us-east-1 with eu-west-1** 

6. Delete these files in the origin bucket, and replace them with the updated versions.

7. Don't forget to make the files public. 

8. Your /index.html and /parent.html pages should now load resources (including the bot) correctly. IF you get a Cognito 400 about not being able to access the resources, check if the call is referencing the **us-east-1** endpoint. If it is, simply update the **lex-web-ui-loader-config.json** file to reference an identity pool in us-east-1. All this is for is the unauth role to call Lex:PostText, Lex:PostContent and Polly:SynthesizeSpeech.

Hope that helps!
