### ISSUE TITLE
loading ui in my s3 bucket says lex-web-ui.css is 403 forbidden through loader

### ISSUE THREAD

**Issue by edenhare** [aws-samples/aws-lex-web-ui#165]
i have copied the dist files to my s3 bucket and added the config to point to my bot.  When I try to load index.html, i get an error that lex-web-ui.css is 403 forbidden.  however, if i go to the path where the fie is located, i can view the file.  the error in chrome shows the path as /./lex-web-ui.css, which is wrong - it should be ./lex-web-ui,css but i cannot see where the leading / is being added.

**Comment by labrlearning** [comment]
Some additional comments- 
the path to the page is bucket/folder/index.html

http://quartermoonfarm.s3.amazonaws.com/resources/lindex.html

Chrome's console says:
**dependency-loader.js:215 GET https://quartermoonfarm.s3.amazonaws.com/lex-web-ui.css net::ERR_ABORTED 403 (Forbidden)**
(anonymous) @ dependency-loader.js:215
F @ _export.js:35
addDependency @ dependency-loader.js:183
(anonymous) @ dependency-loader.js:91
Promise.then (async)
(anonymous) @ dependency-loader.js:90
(anonymous) @ dependency-loader.js:89
load @ dependency-loader.js:89
load @ index.js:88
load @ index.js:127
(anonymous) @ index.html:68
dependency-loader.js:196 Uncaught (in promise) Error: failed to load lex-web-ui dependency link: /./lex-web-ui.css
    at HTMLLinkElement.el.onerror (dependency-loader.js:196)

This shoudn't be a CORS issue.

but if you see the path to lex-web-ui.css, the path is incorrect because the file is actually located at https://quartermoonfarm.s3.amazonaws.com/resources/lex-web-ui.css

Coying the file into the root of the bucket doesn't change the behavior.  The file is marked as public.

**Comment by labrlearning** [comment]
Additional comments - if i try to load the file locally into chrome, the chrome web console reports it cannot load 
dependency-loader.js:215 GET file:///lex-web-ui.css net::ERR_FILE_NOT_FOUND

this is not a relative path

**Comment by ojo-john** [comment]
Did you ever figure this out?

**Comment by labrlearning** [comment]
I don't honk so, but I would have to go check now.  That was a long time ago.
