### ISSUE TITLE
Invoke a Dummy Intent without the message showing up in the Chat Box

### ISSUE THREAD

**Issue by sumeet-kumar-deloitte** [aws-samples/aws-lex-web-ui#220]
In the snippet at the bottom, I send an utterance "dummy" to Lex from the front end. This is invoking my DummyIntent as expected with only the caveat that it looks like the user has typed in "dummy" from the front end. (see below image)
![image](https://user-images.githubusercontent.com/63399583/84765812-654ee280-afed-11ea-91ab-cafc9a2abed2.png).

Is there a way to hide this initial message from the front end to Lex and only see the "bot's" response to the utterance.

Appreciate any help in advance. 

  var loaderOpts = {
    baseUrl: 'my_bucket',
    shouldLoadMinDeps: true
  };
  var loader = new ChatBotUiLoader.IframeLoader(loaderOpts);
  loader.load()
   .then(function () { 
     loader.api.startNewSession();
     loader.api.postText('dummy');
   })
    .catch(function (error) { console.error(error); });

**Comment by reegz** [comment]
If I understand, you're trying to initialise the conversation with a response from the bot and to accomplish this you want to send through a fake or dummy message to Lex.

Perhaps try setting a value for the BOT_INITIAL_TEXT property. This is will display an initial message to the visitor and could prompt them to enter some information which will kick off the interaction with the Lex bot.

I would suggest that this is going to be a cleaner method. 

Otherwise you'll need to look at invoking Lex from a custom method when the page loads: "onLoad" event

**Comment by reegz** [comment]
Have a look at this response: 
[https://github.com/aws-samples/aws-lex-web-ui/issues/197#issuecomment-584459169](https://github.com/aws-samples/aws-lex-web-ui/issues/197#issuecomment-584459169)
