### ISSUE TITLE
Change Minimized Chat Icon

### ISSUE THREAD

**Issue by byoungjr-HarrisonMaxwell** [aws-samples/aws-lex-web-ui#238]
Good Afternoon!

Is it possible to change either the Generic Chatbot Icon inside the Round minimized Chatbot Icon or to change the Entire Round Icon to another image?

For example, we are trying to remove the Chatbot icon from this element:
![image](https://user-images.githubusercontent.com/70597458/91885088-2bd55d00-ec55-11ea-99c4-9e618ce10ff1.png)

Thanks!

**Comment by bobpskier** [comment]
I think the only mechanism to change this at the moment is via source code change within lex-web-ui/src/components/MinButton.vue. Inside the template I believe the <v-icon> element could be updated with a desired icon. This vue component handles rendering of the button when minimized and would be the starting point to see if modifications can be made to its appearance.

**Comment by byoungjr-HarrisonMaxwell** [comment]
Thanks for your help!  That did it!

**Comment by moh10024** [comment]
Could you please give details of what exactly you changed in MinButton.vue

**Comment by moh10024** [comment]
Thanks appreciate your help; what could be the best way to replace our custom icon instead of using Material Design Icons

**Comment by bobpskier** [comment]
@moh10024 I've not tried replacing the icons from Material Design. You could replace <v-icon> with your own component that displays an SVG or you could try to inject a new custom icon into Vuetify and continue to use v-icon.

LexWebUi is on a really old version of vuetify and I'm not entirely sure this version supports configurable icons. If it does you'll be creating a custom component which contains the svg icon code in a separate Vue.js file. Next you'd have to figure out how to adjust the Vuetify config to inject the custom icon. Lex web ui uses a default vuetify.js config obtained from the vuetify dependency. Updating this config is what would need some research. Finally the MinButton.vue would reference this custom icon instead of "chat".

Two references I found are 

https://stackoverflow.com/questions/51614557/how-to-add-custom-svg-icon-in-vuetify-vue

and

https://vuetifyjs.com/en/features/icon-fonts/

I did just now try upgrading vuetify to version 2.6.4 via package.json dependency and this seemed to build and work correctly.  The key still would be to figure out how to inject a custom icon in vuetify config.
