### ISSUE TITLE
Adding a persistent "Contact Live Agent" button

### ISSUE THREAD

**Issue by efuellas** [aws-samples/aws-lex-web-ui#246]
Hi.

I was thinking of adding a persistent / permanent button above the text input field. The idea is for it to be a "Contact Live Agent" button that will redirect to a link when clicked. Is there a way to do this? And if there is, what file should I put this in?

Hope you can help me.

Thanks

**Comment by rstrahan** [comment]
That's a great idea, but probably not trivial to implement unless you are a Vue programmer.  But if you wanted you could re-purpose the existing 'help' button for that.. When you install lex-web-ui you can choose which utterance gets sent when you click the Help buttton on the title bar (?) so you could make it send the 'Contact Agent' utterance instead of Help.
Other folks might have additional suggestions.

**Comment by efuellas** [comment]
Hi rstrahan,

Thanks for that really nice suggestion. Might result to that if there's no better way to do it.

Really appreciate it

**Comment by karanakatle** [comment]
> That's a great idea, but probably not trivial to implement unless you are a Vue programmer. But if you wanted you could re-purpose the existing 'help' button for that.. When you install lex-web-ui you can choose which utterance gets sent when you click the Help buttton on the title bar (?) so you could make it send the 'Contact Agent' utterance instead of Help.
> Other folks might have additional suggestions.

@rstrahan Could you please tell me how to achieve this in vue programming

**Comment by karanakatle** [comment]
In addition to that in lex-web-ui.min.js you can change the help icon to a button a provide a destination link to it through href
also you can modify the buttons as per your need. just change v-icons to v-btn for the components you want to change, add href attribute as a key and pass the link as a value in it. 

Refer to [Documentation page for additional help](https://vuetifyjs.com/en/components/buttons/)
