### ISSUE TITLE
Changes  in lex-web-ui components not visible when deploying

### ISSUE THREAD

**Issue by jgallegor** [aws-samples/aws-lex-web-ui#270]
I have prepared the project in aws with pipeline and codecommit. Was able to make a few changes like toolbar title, or initial message, but when it comes to vue components in lex-web-ui folder the changes are not visible.
This is the steps I make to deploy changes:
- "npm run build" on lex-web-ui folder.
- "npm run build" on root folder.
- Commit and push changes to commit repo.
- Wait for pipeline to compile and see the results. Nothing changes.

Any idea of what I'm missing?

**Comment by bobpskier** [comment]
The lex-web-ui is accessed via a CloudFront distribution. Make sure to invalidate your CloudFront distribution such that new changes are pushed out through CloudFront. It's also worth making sure your browser is reloading its cache as well.

**Comment by jgallegor** [comment]
How can I achieve that (invalidate CloudFront distribution)? 
Sorry for my ignorance...

**Comment by bobpskier** [comment]
In the AWS Console, open the CloudFront console in the region you are working in.  You can key in CloudFront to the "Search for services, features ...". For the lex-web-ui you should see a CloudFront distribution in the table below. Click on the link available in the ID column.  Click on the "Invalidations" tab and click the button "Create Invalidation". Type "*" in the Object Paths text area and click on "Invalidate".  It takes a minute or two to invalidate. Once its complete you can refresh your browser and clear its cache as well. CloudFront is configured with a TTL of 86400 or 24 hours before it would reload from the S3 bucket origin.

**Comment by jgallegor** [comment]
Thanks! It was so helpful.

**Comment by HardikaDoshi** [comment]
Hi, 
I am new to node and vue.
I have tried making some changes in the vue files and when I run 'npm build' and then 'npm start' in the lex-web-ui folder I can see those changes. After that I ran both the commands in the 'aws-lex-web-ui' folder. The changes are not reflected there.
Can you please tell me the steps so that I can make changes in the components.
(Note - For deploying the project I have used the cloud formation method and copied the config file locally)
