### ISSUE TITLE
Getting Error while deployed from cloud formation

### ISSUE THREAD

**Issue by dileephell** [aws-samples/aws-lex-web-ui#29]
I am following this URL : https://aws.amazon.com/blogs/machine-learning/deploy-a-web-ui-for-your-chatbot/.

The parent url and web url both are working fine after creation. The snippet url which i got and adding to my HTML file then i am getting this error.

actions.js:656 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://dataprocessor-codebuilddeploy-lcomu6-webappbucket-l97imh236z77.s3.amazonaws.com') does not match the recipient window's origin ('http://localhost:3000')

Followed this one as well https://github.com/davidjbradshaw/iframe-resizer/issues/443 but hardluck.

can anyone please tell me how to remove this error or where i am going wrong.

**Comment by micaweb** [comment]
Hello @dileephell , were you able to circumvent this eventually?

**Comment by dileephell** [comment]
@micaweb : Nups I didnt.

**Comment by JohnCalhoun** [comment]
From [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/Window.postMessage):

> The window.postMessage method safely enables cross-origin communication. Normally, scripts on different pages are allowed to access each other if and only if the pages that executed them are at locations with the same protocol (usually both http), port number (80 being the default for http), and host (modulo document.domain being set by both pages to the same value).

**Comment by DVGalarza** [comment]
@dileephell You're getting this error because the `WebAppParentOrigin` parameter in your CloudFormation stack and the origin of the application (`http://localhost:3000`) are different, so window.postMessage is getting blocked for security reasons.

To fix, relaunch the CloudFormation stack from the [tutorial](https://aws.amazon.com/blogs/machine-learning/deploy-a-web-ui-for-your-chatbot/), this time setting the WebAppParentOrigin to `http://localhost:3000`, instead of leaving blank. Reconnect your app to this new stack. Now, the origins should match up correctly and allow communication with the iFrame.
