### ISSUE TITLE
Some text messages are not getting

### ISSUE THREAD

**Issue by RoiRovan** [aws-samples/aws-lex-web-ui#339]
I have a lex bot integrated with lambda. Working fine in lex itself.But in lex web ui, some messages are not getting..more specifically closing messages are not getting."Sorry, I was unable to process your message. Try again later" is displaying.  Please help me with this.

**Comment by RoiRovan** [comment]
![20211124_122201](https://user-images.githubusercontent.com/94952922/143189542-f0b9efde-2120-4e6b-a714-9090a52bd03a.jpg)
This is the response back from ui

**Comment by bobpskier** [comment]
Since you are using Lambda, usually the "Sorry, I was unable to process your message. Try again later" indicates some failure in the lambda execution or perhaps exceeding 30 seconds. Do any of the requests displayed in network traffic indicate a failure of some sort. Do the log streams for the lambda function indicate any exception? The example image above shows an ElicitIntent rather than a Close. My guess is the actual close is failing and you'll see an error in log if it is being captured. Does the lambda log it's response to Lex? It would be good to make sure this response is valid.

**Comment by RoiRovan** [comment]
But Lambda is executing fine in lex itself.No error logs in log streams also.In lex web ui, Closing messages of all intents are not getting.

**Comment by bobpskier** [comment]
If Lambda is not showing an error, the next place to look for an error would be in the browser console log. Let me know if you see an error message in the browser that might be helpful. 

I could not reproduce the problem when setting close messages via the AWS Lex V2 console for an intent. They display correctly and result in a dialogAction of type "Close" which is a bit different than the image above. 

```
"sessionState": {
        "dialogAction": {
            "type": "Close"
        },
```

Is there a url you can share where I can see the problem or perhaps you can share the Lambda response object for the request that is not being processed and I can attempt to duplicate?

**Comment by bobpskier** [comment]
If you can supply the Lambda response object or the network response for the postText or postContent captured in browser we can try and assist further. Please reopen the issue with additional data as needed.
