### ISSUE TITLE
Guide for building dist folder

### ISSUE THREAD

**Issue by HardikaDoshi** [aws-samples/aws-lex-web-ui#343]
Hi, can you please tell the steps for building the dist folder after we make change in the lex-web-ui folder?

**Comment by bobpskier** [comment]
The best mechanism to use to rebuild LexWebUi is to use the release script in the build folder. This will also update contents in the dist folder when complete. 
```
cd build
./release.sh
```

In this script you will see the entire build process including the npm run commands used to build and the additional make commands that setup resources needed if enabling deployment via your own bootstrap s3 bucket. 

Builds can be performed on Linux and OSX or via the Cloud9 IDE running Amazon Linux. Builds are not supported on Windows unless using the Windows Subsystem for Linux.

**Comment by HardikaDoshi** [comment]
Thank you. 
Just a follow up question -
I have implemented this repo using the cloud formation method.
So how do I upload the built dist folder to the the s3 bucket?

**Comment by bobpskier** [comment]
Not sure what you mean by have implemented using the cloud formation method. 

The technique below allows you to create a new build of LexWebUi on your own system and upload this to an your own S3 bucket from which you can update an existing LexWebUi instance or create a new LexWebUi instance. 

The S3 bucket you are uploading to would be known conceptually a "bootstrap" bucket. You can use the following to complete this upload. In the present implementation this bucket needs to allow objects to have public-read acl.

```
cd build
./release.sh
export BUCKET="yourbootstrapbucketname"
./upload-bootstrap.sh
```
From this "bootstrap" bucket you can either deploy a new installation of lexwebui using the template in your bucket or update existing deployments of lexwebui using the same template. Note: when deploying or updating from your template using the AWS CloudFormation console or via cli, change the bootstrap bucket parameter to use the name of your bootstrap bucket instead of the publicly available distribution.

**Comment by bobpskier** [comment]
Added small section to toplevel readme describing process to update dist and update a bootstrap bucket.
