### ISSUE TITLE
Response cards buttons overlapping on each other

### ISSUE THREAD

**Issue by AbhishekDesai99** [aws-samples/aws-lex-web-ui#366]
Buttons are overlapping on each other.
We are using IFrame loader and due to which the window size is almost like mobile view size. Everything is running fine, but for few buttons where text size is longer, it will get overlapped with the next response card's buttons.
![Screenshot from 2022-03-20 13-47-59](https://user-images.githubusercontent.com/55693856/159154127-b2fa55a5-66b0-465d-b268-fdadd20677e5.png)

As you can see in the above picture, I chnged the button rendering as column instead of row. So there will be a column for a response card, and everytime there will be two response cards. One card for suggestion based buttons and next card for navigation based buttons.

Can we do something from css side to fix this issue ?
http://iframe-holder.s3-website-us-east-1.amazonaws.com/
Here is my bot, you can check manually too.

**Comment by bobpskier** [comment]
Is there a requirement to return two response cards? Lex has a restriction on the number of buttons in a single response card. However, Lex Web Ui supports higher number of  buttons in a responseCard using the appContext.responseCard object as a session attribute. See https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/README.md#response-cards for the mechanism to add a responseCard to the session attribute appContext. If you need 10 buttons you can return the responseCard with 10 buttons in this session attribute and lex web ui will display all ten. This might let you use the default row style and let the current css position these better. 

CSS solutions will require seeing what vuetify can do with this rendering. The best that might be possible is to wrap the second column to a new column or to have vuetify try and reduce the size of the content so that it might fit better. Vuetify has some content that describes some of the css within their grid system. https://vuetifyjs.com/en/components/grids/.

**Comment by AbhishekDesai99** [comment]
@bobpskier thank you, I can definitely try this.

**Comment by bobpskier** [comment]
@AbhishekDesai99 Yes, it is compatible with Lex V1 bots as well. The following example comes from QnABot which this case is providing ten buttons. appContext is a string value with embedded json. Session attributes in lex can't use json property / value structures directly. 

```
"sessionAttributes": {
      "appContext": "{\"altMessages\":{},\"responseCard\":{\"version\":\"1\",\"contentType\":\"application/vnd.amazonaws.card.generic\",\"genericAttachments\":[{\"title\":\"Test Buttons\",\"buttons\":[{\"text\":\"Button One\",\"value\":\"Button One\"},{\"text\":\"Button Two\",\"value\":\"Button Two\"},{\"text\":\"Button Three\",\"value\":\"Button Three\"},{\"text\":\"Button Four\",\"value\":\"Button Four\"},{\"text\":\"Button Five\",\"value\":\"Button Five\"},{\"text\":\"Button Six\",\"value\":\"Button Six\"},{\"text\":\"Button Seven\",\"value\":\"Button Seven\"},{\"text\":\"Button Eight\",\"value\":\"Button Eight\"},{\"text\":\"Button Nine\",\"value\":\"Button Nine\"},{\"text\":\"Button Ten\",\"value\":\"Button Ten\"}]}]}}",
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0"
    }
 ```
