### ISSUE TITLE
AWS lex-web-ui Build failure 

### ISSUE THREAD

**Issue by ladabhi** [aws-samples/aws-lex-web-ui#397]
Hi i am trying to do a prod build in visual studio code on windows. In the build directory i used ./release.sh
I got the following error:
Build Target is not recognised as an internal or external command
make command not found

Can anybody help me in this?

**Comment by bobpskier** [comment]
@ladabhi The only way to successfully build on a windows system using the release.sh script is to use the Windows Subsystem for Linux.  https://docs.microsoft.com/en-us/windows/wsl/about. This provides the necessary tooling to execute a build. Otherwise Mac OSX, or a pure Linux system, or a Cloud 9 system in AWS using Amazon Linux 2 would be necessary.
