### ISSUE TITLE
How can we Integrate LexV2 chatbot with multiple websites by using single cloud formation stack

### ISSUE THREAD

**Issue by sv1033** [aws-samples/aws-lex-web-ui#496]
How can we Integrate LexV2 chatbot with multiple websites(2 or more, up to 100) by using single cloud formation stack.

I dont want to create  a new cloud formation stack for a each website I integrate Lex chatbot. Just with one CloudFormation stack, I should be able to integrate multiple websites.
write now **WebAppParentOrigin** field in the template is not taking more than one origin.  Do we have a solution for this ?

**Comment by bobpskier** [comment]
@sv1033 The default configuration and javascript source prevents use of the UI on multiple parent origins. CORS configuration, cognito identity pool config, and java script code checks prevent this type of configuration. 

Is any sort of authentication required by the UI? Will it service anyone using the unauth role associated with the cognito identity pool? 

If the answer is No to authentication and Yes that the unauth role will suffice, one could fork this repo and create a custom code base that sets CORS to "*" in the relevant locations to allow any site to load the iframe . In addition one could comment out the javascript code checks to ensure correct parent origin and allow all internal api requests from the parent page to the iframe to be processed. 

The theory then is that the resulting code snippet could be used on the 100 parent origins. However, it is not best practice to allow the iframe to be loaded from anywhere but there is no other way to scale it to 2 to 100+ parent origins. 

One could also fork the code base and utilize the Vue component(s) and load these directly on the 100 parent pages bypassing the iframe mechanism entirely. Hence CORS is no longer an issue with respect to iframe use. It will take a decent amount of effort to work with the Vue components directly which is why the iframe approach is used.

**Comment by sv1033** [comment]
@bobpskier  Thank you for your reply.  No need of any authentication from the UI, just unauth role associated with cognito pool will be fine.  
Can you explain why it is not a good practice to load up to 100 iframes? each website is different and all would be integrated with lex chatbot and this iframe is independent to each other though source is same. will it lead to a performance issues ?

**Comment by Edwardiv1** [comment]
This was marked as completed, but what was the solution/change?

**Comment by atjohns** [comment]
@Edwardiv1 There was no solution or change to this code branch - as noted above it is possible by bypassing some of the security that comes baked in to the solution. You could follow the instructions provided above and make this work, its just not something we are going to do in this repo as it would allow anyone to put your chatbot on their own website.

**Comment by Edwardiv1** [comment]
Thanks. I was hoping for something like WebAppParentOrigin = *.mysite.com to be allowed, which solves this issue for multi-tenant sites while still not allowing anyone to put the chatbot on their own website.

**Comment by atjohns** [comment]
@Edwardiv1 Gotcha, yeah I think that would be possible - could maybe look into how that would work functionally without removing the CORS or parent/child relationship

**Comment by Edwardiv1** [comment]
That would be a game-changer. For anyone managing 50+ subdomains, the only current workaround is writing a custom proxy, which is a major headache and comes with a lot of baggage.
