### ISSUE TITLE
WebAppConfBotInitialSpeech overwriting initialSpeechInstruction in JSON config & speaking every time

### ISSUE THREAD

**Issue by st7788** [aws-samples/aws-lex-web-ui#526]
The param `WebAppConfBotInitialSpeech` which is defined in the lex-web-ui CloudFormation stack, is overwriting the `initialSpeechInstruction` param that is defined lex-web-ui-loader-config.json file. The value `initialSpeechInstruction`, is ignored and the the string from the CloudFormation stack is spoken every single time the user clicks the microphone icon in the UI. 

We want to have a dynamic initial speech instruction, and only deliver the spoken instruction once when using TTS for the first time during the session.

**Comment by atjohns** [comment]
WebAppConfBotInitialSpeech maps to initialSpeechInstruction when the CloudFormation stack is deployed or updated. This is intended behavior because changes to the CFN stack will always overwrite what's on the json config file - if you want to retain those changes please make them in the stack as well so that future updates will not override manual configuration changes.

Similarly, the Web UI plays the audio instructions every time the user toggles back to audio from text input. This is intended behavior, but as an open source solution you are welcome to fork and make updates to change this behavior so that it only plays once for your specific use case. The code for this behavior can be found [here](https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/src/components/InputContainer.vue).
