### ISSUE TITLE
Transferring to Agent

### ISSUE THREAD

**Issue by mtupuri** [aws-samples/aws-lex-web-ui#542]
<img width="618" alt="ConnnectLiveChatTerms" src="https://github.com/aws-samples/aws-lex-web-ui/assets/144356563/c56a7f28-75d6-492d-bb54-676e42bbfccc">
<img width="663" alt="issue" src="https://github.com/aws-samples/aws-lex-web-ui/assets/144356563/0c57ef98-7bb2-4e0a-9284-5d1f92e4749c">
In order to transfer to agent from the QnAChat first we have to use any of the keywords used in the "ConnectLiveChatTerms" and in the next iteration user need to type "agent" to connect to live agent. Additionally, QID ConnectHelper.Agent (speak to agent) is not helping to transfer to live agent as well.

**Comment by atjohns** [comment]
It looks like you are using the 'PromptforName' parameter incorrectly here, the chat will wait for a response from the user if you have this populated. What happens when you remove that parameter from the template?

**Comment by israelias** [comment]
@mtupuri Perhaps you've already fulfilled the Name prompt in session. Otherwise it seems Start Live Chat is not hitting the right hook but queue for live chat on `agent` trigger seems live.
 
We were able to fully utilize the Connect stack `speak to an agent` or `can you call me` by following the catalog workshop with the imported Example(s). But it had to either be separate contact flows (from the Start Live Chat button vs a module with lambda to callback fulfillment).  Also, had to remove two other examples that were triggering `agent` or something synonymous to it. 

In case that might be helpful
