### ISSUE TITLE
Change Color of Dialog?

### ISSUE THREAD

**Issue by patran** [aws-samples/aws-lex-web-ui#62]
How do we change the colors? The title bar, the background, the text background and would it be possible to add an icon to the title bar?

**Comment by Yogeshwar1992** [comment]
Dear patran,

did you get the solution?

**Comment by germanAdrian** [comment]
Hey,
you can change message-, response card colors and Toolbar Color in the Vue Components under aws-lex-web-ui/lex-web-ui/src/components/.
 
Example:
from Message.vue there you can change the style

```
.message-human .message-bubble {
  background-color: #E8EAF6; /* indigo-50 from material palette */
}
```
-> changes color for human messages

Changes for Toolbar are a bit more complicated. You can change the Vue template (=LexWeb.vue) to use a specific color, instead of using the color from config files.

But to change toolbar color, I like the following approach:
Changing the colors specified by vuetify (eg: red lighten-5). 
You can download the vuetify.css and do changes there.
So you can still change color to a specific identifier in lex-web-ui/src/config/index.js
`toolbarColor: 'adriansIdentifierAddedToVuetify.css',`

Therefor you want to change the dependency to a local file instead of downloading from 
https://unpkg.com/vuetify@0.17.6/dist/vuetify.css
 You can do this in the dependencies.js under src/lex-web-ui-loader/js/defaults
```
    {
      name: 'vuetify',
      url: 'https://unpkg.com/vuetify@0.17.6/dist/vuetify.css',
      canUseMin: true,
    }
```
there change `url `as usual.
This approach feels a lot easier, still uses the implemented logic for the styling and since I have to download these files according to GDPR.

**After these changes use `make` in root to rebuild the dist - files.**

Hope I could help you.

Let me know if it worked / you need more info.

**Comment by CelticRugger** [comment]
you can add some minor adjustments to the lex-web-ui-loader-config.json file snippet below as mentioned above the bubble colours can be customized in the lex-web-ui.css file

From .json config file
------------------------
"ui": {
    "parentOrigin": "https://www.mywebsite.co.uk",
    "toolbarTitle": "My Title",
    "toolbarLogo": "",
    "avatarImageUrl": "https://www.website.co.uk/avatar.png",
    "pushInitialTextOnRestart": false,
    "toolbarColor": "purple"
  },

**Comment by jinot92** [comment]
@germanAdrian could you elaborate on "_After these changes use **make** in root to rebuild the dist - files._". I need to make some changes to the components and rebuild them, I am looking for a way to do so.
