### ISSUE TITLE
lex web ui run build:lib-dev failed when using windows

### ISSUE THREAD

**Issue by Snailmar** [aws-samples/aws-lex-web-ui#691]
I'm using windows to build lex web ui, but I failed with this error, but when i use Mac to build, there is no error. 
![image](https://github.com/aws-samples/aws-lex-web-ui/assets/21135474/38c8121e-970d-4edc-ad4b-51b2a0863bbe)
Please help me to fix it out.

**Comment by atjohns** [comment]
What build command are you using?

**Comment by Snailmar** [comment]
> What build command are you using?

npm run build:lib-dev

**Comment by atjohns** [comment]
I've validated the error and will try to see if I can figure out what's causing it. In the meantime I would recommend using a non-Windows machine to do the build - I use Cloud9 for our builds internally it works well for this

**Comment by israelias** [comment]
@Snailmar 

What node version is your windows running at the child dir `./lex-web-ui` when you execute `npm run build:lib-dev`?

```
"build:lib-dev": "BUILD_TARGET=lib vue-cli-service build --skip-plugins @vue/cli-plugin-eslint ---no-clean --mode development src/lex-web-ui.js",
```

Can you try setting the env var `BUILD_TARGET=lib` in the shell or putting it in `./lex-web-ui/.env`/removing it from the script?

If all other npm scripts in childVueDir/package.json are giving you errors, can you try running the CLI command `vue-cli-service build` directly?

Otherwise, just manually clear the assets in `./lex-web-ui/dist/bundle` between builds if you really have to use windows, and if it's correctly set to the Node version that supports webpack at `cd ..` for whichever tag of the root repo you're at.

**Comment by atjohns** [comment]
A fix for this has been added to the latest release
