### ISSUE TITLE
The chatbox UI not rendering singular newline '\n' character properly

### ISSUE THREAD

**Issue by yaodaniel** [aws-samples/aws-lex-web-ui#694]
content contains the response from a LLM and following is the Lex messages response:

```
messages: [
{
  "content": "The query to get the average metric for each individual day, limited to 20 results, is:\n\nSELECT \n    CAST(SUBSTR(partition_date, 1, 10) AS DATE) AS date,\n    AVG(metric) AS avg_metric\nFROM\n    Table\nGROUP BY \n    CAST(SUBSTR(partition_date, 1, 10) AS DATE)\nORDER BY\n    date  \nLIMIT 20;\n\nThis extracts just the date part from the partition_date column by taking a substring of the first 10 characters and casting it to a DATE type. It then calculates the average metric, groups the results by the extracted date, orders chronologically, and limits to 20 rows.",
  "contentType": "CustomPayload"
}
]
```

I'd expect to see something like the following rendered:

```
The query to get the average metric for each individual day, limited to 20 results, is:

SELECT 
    CAST(SUBSTR(partition_date, 1, 10) AS DATE) AS date,
    AVG(metric) AS avg_metric
FROM
    Table
GROUP BY 
    CAST(SUBSTR(partition_date, 1, 10) AS DATE)
ORDER BY
    date  
LIMIT 20;

This extracts just the date part from the partition_date column by taking a substring of the first 10 characters and casting it to a DATE type. It then calculates the average metric, groups the results by the extracted date, orders chronologically, and limits to 20 rows.
}
```

But instead, I'm seeing something like:

```
The query to get the average metric for each individual day, limited to 20 results, is:

SELECT CAST(SUBSTR(partition_date, 1, 10) AS DATE) AS date, AVG(metric) AS avg_metric FROM Table GROUP BY CAST(SUBSTR(partition_date, 1, 10) AS DATE) ORDER BY date
LIMIT 20;

This extracts just the date part from the partition_date column by taking a substring of the first 10 characters and casting it to a DATE type. It then calculates the average metric, groups the results by the extracted date, orders chronologically, and limits to 20 rows.
```

**Comment by atjohns** [comment]
I'm not sure if this is an issue with the [MarkedJS library](https://github.com/markedjs/marked) that we use or just expected behavior from it, but that is what is causing this issue.

[Here is a demo of the expected output using your Markdown](https://marked.js.org/demo/?text=The%20query%20to%20get%20the%20average%20metric%20for%20each%20individual%20day%2C%20limited%20to%2020%20results%2C%20is%3A%0A%0ASELECT%20%0A%20%20%20%20CAST(SUBSTR(partition_date%2C%201%2C%2010)%20AS%20DATE)%20AS%20date%2C%0A%20%20%20%20AVG(metric)%20AS%20avg_metric%0AFROM%0A%20%20%20%20Table%0AGROUP%20BY%20%0A%20%20%20%20CAST(SUBSTR(partition_date%2C%201%2C%2010)%20AS%20DATE)%0AORDER%20BY%0A%20%20%20%20date%20%20%0ALIMIT%2020%3B%0A%0AThis%20extracts%20just%20the%20date%20part%20from%20the%20partition_date%20column%20by%20taking%20a%20substring%20of%20the%20first%2010%20characters%20and%20casting%20it%20to%20a%20DATE%20type.%20It%20then%20calculates%20the%20average%20metric%2C%20groups%20the%20results%20by%20the%20extracted%20date%2C%20orders%20chronologically%2C%20and%20limits%20to%2020%20rows.&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=12.0.2) which as you can see is not rendering.

**Comment by israelias** [comment]
@yaodaniel Your custom payload is trying to comply with Message content per Lex schema (V2, ideally, but this assumption is a stretch). The handled error will be in your CF backend but there is less than enough context in the issue to isolate what service with which quota is breaking your LLM retrieval. 

First action item would be to ENABLE_DEBUG_RESPONSES in Content Designer, so you can at least offer this frontend issue something more meaningful than broken SQL statements

https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/text-generation-and-query-disambiguation-using-llms.html
